### ISSUE TITLE
[DOCS] New Contribution Guide and Readme file

### ISSUE THREAD

**Issue by achintya-7** [achintya-7/notesApp_flutter#3]
# What
Need to make a new Contribution guide and Readme file
A good reference for these can be amibot's [readme](https://github.com/asetalias/amibot/blob/main/README.md) and [contribution](https://github.com/asetalias/amibot/blob/main/types-of-contributions.md)

# Documentation requirements

- about the project
- software used and their versions
- how to install
- features
- how to contribute

**Comment by kaustav202** [comment]
can I work on the contribution guidelines?

**Comment by achintya-7** [comment]
Sure! This repo is going to get migrated under an org soon. I will ping you and assign the task there then. Please wait up to 3 days.
@ditsuke 👀

**Comment by syedzubeen** [comment]
@achintya-7 
Is this issue still open?
If yes, I can work on this if unassigned.

**Comment by achintya-7** [comment]
@syedzubeen @kaustav202 

Will you be able to make both readme and contribution guide.

**Comment by syedzubeen** [comment]
@achintya-7 
Yes, I can do both.

**Comment by achintya-7** [comment]
@syedzubeen 
Good! Assigning the issue to you.

**Comment by syedzubeen** [comment]
Both files have been added. 
Refer to this pull request: #4

**Comment by achintya-7** [comment]
@syedzubeen Minor changes required. Just go through the comment.

**Comment by syedzubeen** [comment]
Done @achintya-7

**Comment by achintya-7** [comment]
Thank you @syedzubeen. If you want to work on other issues as well, feel free to ping me.
